# Generated by Django 2.2.1 on 2020-02-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_num', models.CharField(max_length=15, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('out_data', models.DateTimeField(verbose_name='出生日期')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('study_subject', models.CharField(max_length=32, verbose_name='学习科目')),
            ],
        ),
    ]
