# Generated by Django 2.2.1 on 2020-02-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demodata', '0002_students_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=20, verbose_name='老师姓名')),
                ('t_subject', models.CharField(max_length=32, verbose_name='授课科目')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
