# Generated by Django 2.2.1 on 2020-02-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demodata', '0003_teachers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
